name: CI/CD - Build, Test, and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ success() }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t my-flask-app:latest .

      - name: Push Docker image
        run: |
          docker tag my-flask-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest

